### ISSUE TITLE
[Bug] - sonarr tba update script incorrect path / unable to locate series

### ISSUE THREAD

**Issue by nicktags** [goose-ws/bash-scripts#18]
With the most recent updated script, it's unable to locate the proper directory or find the series to update.  It looks like it's pulling the path in the container and not the path of the actual system.  For example, in sonarr I might have the path in the container point where

/NAS/TV = /share/data/TV

It's pulling the first directory /NAS/TV which does not exist in my system.  It needs the second path.

I manually changed this in the script to point to the correct directory but now every TBA comes back with unable to locate series.

Thanks in advance, these are great scripts!

**Comment by goose-ws** [comment]
Just to clarify, `/NAS/TV` is a virtual docker mount, and `/share/data/TV` is the physical path?

You're using sonarr in docker, and not bare metal install?

Also, what is your `containerIp=` line from your config?

*Edit:*

Also, which version are you using that works for you? My most recent update [was just some verbiage changes](https://github.com/goose-ws/bash-scripts/commit/16a84cab941c2f00df56e10e0749f458519d075d#diff-7dd5cb61e8f5140f8c5e4f46b6fa4660dbc4e9fd8eab992a06fdb611e006e4c2), not any of the code that processes files.

**Comment by nicktags** [comment]
Correct, I'm using docker and it's reading the virtual mount causing the error.  Even after hard coding the true directory in the script, it's able to locate any series to update.  The container ip I set to local or 127.0.0.1.  I can see in the command lines it connects fine.

**Comment by goose-ws** [comment]
If you're using Docker, it *should* be searching the virtual mount, from inside the container where that path will exist/be valid.

The script differentiates if it should use a physical path or a virtual mount inside the container by looking for the "docker:" prefix in your `containerIp` value. Specifically, [line 618](https://github.com/goose-ws/bash-scripts/blob/d9d0aad6b26d577b326088f1326c1ab596317807/sonarr-update-tba.bash#L618):

    if [[ "${containerName%%:*}" == "docker" ]]; then

So `containerIp=("docker:sonarr")` tells the script to look at the virtual mount from inside the container, [line 627](https://github.com/goose-ws/bash-scripts/blob/d9d0aad6b26d577b326088f1326c1ab596317807/sonarr-update-tba.bash#L627):

    docker exec "${containerName#docker:}" find "${i}" -type f -regextype egrep -regex "${findRegex}" | tr -d '\r' | sort

Versus if the value contains anything *other* than starting with that `docker` prefix, [line 638](https://github.com/goose-ws/bash-scripts/blob/d9d0aad6b26d577b326088f1326c1ab596317807/sonarr-update-tba.bash#L638):

    find "${i}" -type f -regextype egrep -regex "${findRegex}" | tr -d '\r' | sort

Although I'm now realizing that for that second `find` command, I can drop the `tr -d '\r'` since Unix won't append that carriage return. But that's unrelated.

Assuming your docker container name is "sonarr", you can use `containerIp=("docker:sonarr")` and the script will get the virtual mount from Sonarr and then search that path from inside the container, where it does exist. If you're already using `containerIp=("docker:sonarr")` and it's unable to find your files with a hard coded path, then something is more wrong. In that case, set verbosity to 3 and send me the output of your script (you can use the email in my profile if you'd rather not paste it here).

**Comment by nicktags** [comment]
I did have it set to docker:sonarr and it was telling me the directory didn't exist.  I'll set it to verbosity when I get home and let you know what the output is.  Thanks!

**Comment by nicktags** [comment]
It appears to be working now.  Thanks for pointing me to those lines in the code.
