### ISSUE TITLE
Missing / for base url

### ISSUE THREAD

**Issue by Catvari** [goose-ws/bash-scripts#7]
The / is not added to the base url so every curl request are failing.
To fix the problem, I just added it line 503: `sonarrUrlBase="/${sonarrUrlBase%</UrlBase>}"`

Thanks for your work

**Comment by goose-ws** [comment]
On an unrelated note, thanks for leading me to notice a copy/paste typo I made on line 504.

The `/` is added on [line 514](https://github.com/goose-ws/bash-scripts/blob/7fb553b515b4fa215173cec98750c88e554ee283/sonarr-update-tba.bash#L514):

    apiCheck="$(curl -skL "${containerIp}:${sonarrPort}${sonarrUrlBase}/api/v3/system/status" -H "X-api-key: ${sonarrApiKey}" -H "Content-Type: application/json" -H "Accept: application/json")"
                                                                       ^here

So you shouldn't need to edit line 503. What is your `URL Base`, from your `Settings > General > Host > URL Base` page?

**Comment by goose-ws** [comment]
Oh you mean the *prefix* `/`?

I assume your `URL Base` is something like `sonarr` instead of `/sonarr`. I was expecting the behavior that one would prefix their URL Base with a `/`, as described [in the URL Base section of the config wiki](https://wiki.servarr.com/sonarr/settings#host):

    URL Base - For reverse proxy support, default is empty
    Note: If using a reverse proxy (example: mydomain.com/sonarr) you would enter '/sonarr' for URL Base.

I can add a safety/sanity check for padding with a prefix `/` if necessary, but I believe you should be prefixing your URL Base with `/` in the settings page.

**Comment by Catvari** [comment]
My URL base was appearing to be /sonarr in sonarr but the / wasn't in the config file. I've edited the base url and now it's saved properly in the config.
